Refine some of the citus startup scripts to handle more dns update delays

diff --git a/charts/lokahi/templates/citus/citus-worker-statefulset.yaml b/charts/lokahi/templates/citus/citus-worker-statefulset.yaml
--- a/charts/lokahi/templates/citus/citus-worker-statefulset.yaml
+++ b/charts/lokahi/templates/citus/citus-worker-statefulset.yaml
@@ -53,7 +53,6 @@ spec:
         - -c
         - |
           sh <<'SH' &
-          export PGPASSWORD="P@ssword123"
           node_name=${HOSTNAME}.citus-worker.${POD_NAMESPACE}.svc.cluster.local;
 
           echo [$(date -Iseconds)] Wait pg_isready;
@@ -62,19 +61,17 @@ spec:
           echo [$(date -Iseconds)] pg is ready;
           # wait for extension
           sleep 5;
-          # extra wait for name to be available on the coordinator
-          sleep 55;
 
           echo [$(date -Iseconds)] Wait name resolve ${node_name};
           timeout 10m sh -c "until nslookup ${node_name} > /dev/null; do sleep 2; done;";
-          nslookup ${node_name} > /dev/null || { echo Name not ready; kill -9 1; exit 1; }
 
           echo [$(date -Iseconds)] Wait manager;
           timeout 5m sh -c "until psql 'host=citus user=desenv' -c 'SELECT citus_is_coordinator()' > /dev/null; do sleep 2; done;";
           psql 'host=citus user=desenv' -c 'SELECT citus_is_coordinator()' > /dev/null || { echo Manager not ready; kill -9 1; exit 1; }
 
+          # Wait and retry as the DNS name may take longer to be available on the coordinator
           echo [$(date -Iseconds)] citus_add_node ${node_name};
-          psql 'host=citus user=desenv' -c "SELECT * from citus_add_node('${node_name}', 5432);" || {
+          timeout 5m sh -c "until psql 'host=citus user=desenv' -c \"SELECT * from citus_add_node('${node_name}', 5432);\"; do sleep 5; done" || {
             echo citus_add_node failed;
             kill -9 1;
           }
